// Generated by CoffeeScript 1.5.0
(function() {
  var AngularTemplateCompiler;

  module.exports = AngularTemplateCompiler = (function() {

    AngularTemplateCompiler.prototype.brunchPlugin = true;

    AngularTemplateCompiler.prototype.type = 'template';

    AngularTemplateCompiler.prototype.extension = 'html';

    function AngularTemplateCompiler(config) {
      var _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      this.moduleName = ((_ref = config.plugins) != null ? (_ref1 = _ref.angularTemplates) != null ? _ref1.moduleName : void 0 : void 0) || 'templates';
      this.filenameOnly = ((_ref2 = config.plugins) != null ? (_ref3 = _ref2.angularTemplates) != null ? _ref3.filenameOnly : void 0 : void 0) || false;
      this.prependPath = ((_ref4 = config.plugins) != null ? (_ref5 = _ref4.angularTemplates) != null ? _ref5.prependPath : void 0 : void 0) || '';
    }

    AngularTemplateCompiler.prototype.compile = function(data, path, callback) {
      var result, stringifyTemplate;
      if (this.filenameOnly) {
        path = path.replace(/^.*[\\\/]/, '');
        path = this.prependPath + path;
      }
      stringifyTemplate = function(str) {
        var stringArray;
        stringArray = '[';
        str.split('\n').map(function(e, i) {
          return stringArray += "'" + e.replace(/'/g, "\\'") + "',";
        });
        return stringArray += "''" + '].join("\\n")';
      };
      result = "(function() {\n  var module;\n  try {\n    module = angular.module('" + this.moduleName + "');\n  } catch (error) {\n    module = angular.module('" + this.moduleName + "', []);\n  }\n  module.run(['$templateCache', function($templateCache) {\n    return $templateCache.put('" + path + "', " + (stringifyTemplate(data)) + ");\n  }])\n})();";
      return callback(null, result);
    };

    return AngularTemplateCompiler;

  })();

}).call(this);
